target-version = "py312"
line-length = 100
select = ["ALL"]
ignore = [
    "A003",    # builtin-attribute-shadowing
    "ANN002",  # missing-type-args
    "ANN003",  # missing-type-kwargs
    "ANN1",    # flake8-annotations Method Annotations
    "ANN201",  # missing-return-type-undocumented-public-function
    "ARG002",  # unused-method-argument
    "BLE001",  # blind-except
    "C90",     # mccabe
    "COM812",  # missing-trailing-comma
    "D1",      # pydocstyle Missing Docstrings
    "D203",    # one-blank-line-before-class
    "D205",    # blank-line-after-summary
    "D213",    # multi-line-summary-second-line
    "E731",    # lambda-assignment
    "EM",      # flake8-errmsg
    "FBT",     # flake8-boolean-trap
    "INP",     # flake8-no-pep420
    "INT",     # flake8-gettext
    "N818",    # error-suffix-on-exception-name
    "PLR0912", # too-many-branches
    "PLR0913", # too-many-arguments
    "PLR2004", # magic-value-comparison
    "RUF001",  # ambiguous-unicode-character-string
    "S311",    # suspicious-non-cryptographic-random-usage
    "S603",    # subprocess-without-shell-equals-true
    "S607",    # start-process-with-partial-path
    "SLF",     # flake8-self
    "TCH",     # flake8-type-checking
    "TD002",   # missing-todo-author
    "TD003",   # missing-todo-link
    "TRY003",  # raise-vanilla-args
    "TRY400",  # error-instead-of-exception
]
ignore-init-module-imports = true

[per-file-ignores]
"arabot/core/__init__.py" = ["F401", "F403"]
"arabot/utils/__init__.py" = [
    "F401", # unused-import
    "F403", # undefined-local-with-import-star
]
"arabot/modules/eval/client.py" = ["PGH001", "S307"] # Allow the use of eval

[format]
docstring-code-format = true

[lint.flake8-annotations]
mypy-init-return = true
allow-star-arg-any = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-import-conventions]
banned-from = ["json", "orjson"]

[lint.isort]
classes = ["clean_content", "pfxless"]

[lint.pep8-naming]
ignore-names = []
